---
- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: update arch repositories
      pacman:
        update_cache: yes
        upgrade: yes
        force: yes
      when: ansible_facts['os_family']|lower == 'archlinux'

    - name: update deb repositories
      apt:
        update_cache: yes
        upgrade: yes
        force: yes
      when: ansible_facts['os_family']|lower == 'debian'

    - name: update fedora repositories
      dnf:
        update_cache: yes
        update_only: yes
      when: ansible_facts['distribution']|lower == 'fedora'

  tasks:
  - name: install packages - base
    package:
      name:
        - htop
        - sakura
        - neovim
        - unzip

  - name: create .fonts directory
    file:
      path: /home/onigiri/.fonts
      state: directory

  - name: install nerd hack fonts
    unarchive:
      src: files/hack-fonts/Hack.zip
      dest: /home/onigiri/.fonts

  - name: download starship prompt
    get_url:
      url: https://starship.rs/install.sh
      dest: /home/onigiri/Downloads/starship.sh

  - name: install starship prompt
    shell: /home/onigiri/Downloads/starship.sh

  - name: copy custom .bashrc file
    copy:
      src: files/bash/bashrc
      dest: /home/onigiri/.bashrc
      owner: onigiri
      group: onigiri

  - name: create sakura config directory
    file: 
      path: /home/onigiri/.config/sakura
      state: directory

  - name: copy sakura config file
    copy:
      src: files/config/sakura/sakura.conf
      dest: /home/onigiri/.config/sakura/sakura.conf
      owner: onigiri
      group: onigiri

  - name: copy .bash_aliases file - arch
    copy:
      src: files/bash/bash_aliases_arch
      dest: /home/onigiri/.bash_aliases
      owner: onigiri
      group: onigiri
    when: ansible_facts['os_family']|lower == 'archlinux'

  - name: copy .bash_aliases file - deb
    copy:
      src: files/bash/bash_aliases_deb
      dest: /home/onigiri/.bash_aliases
      owner: onigiri
      group: onigiri
    when: ansible_facts['os_family']|lower == 'debian'

  - name: copy .bash_aliases file - fed
    copy:
      src: files/bash/bash_aliases_fed
      dest: /home/onigiri/.bash_aliases
      owner: onigiri
      group: onigiri
    when: ansible_facts['os_family']|lower == 'fedora'

#  - name: add ansible user
#    user:
#      name: tractor
#      system: yes
#
#  - name: set up sudo for ansible user
#    copy:
#      src: files/bash/sudoer_tractor
#      dest: /etc/sudoers.d/tractor
#      owner: root
#      group: root
#      mode: 0440
#
#  - name: add ansible-pull cron job
#    cron:
#      name: ansible auto-provision
#      user: tractor
#      minute: "*/10"
#      job: ansible-pull -o -U https://gitlab.com/onigiri070/ansible_workstation.git 
