---
- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: update arch repositories
      pacman:
        update_cache: yes
        upgrade: yes
        force: yes
      when: ansible_facts['os_family']|lower == 'archlinux'

    - name: update deb repositories
      apt:
        update_cache: yes
        upgrade: yes
        force: yes
      when: ansible_facts['os_family']|lower == 'debian'

    - name: update fedora repositories
      dnf:
        update_cache: yes
        update_only: yes
      when: ansible_facts['distribution']|lower == 'fedora'

  tasks:
  - name: install packages - base
    package:
      name:
        - htop
        - byobu
        - zsh

  - name: check if zimrc exists
    stat:
      path: "/home/onigiri/.zimrc"
    register: zimrc_data

  - name: install Zimfw if zimrc does not exist
    become_user: onigiri
    shell:
      cmd: curl -fsSL https://raw.githubusercontent.com/zimfw/install/master/install.zsh | zsh
    when: not zimrc_data.stat.exists

  - name: copy custom zimfw file
    copy:
      src: files/zimrc
      dest: /home/onigiri/.zimrc
      owner: onigiri
      group: onigiri

  - name: copy custom .zshrc file
    copy:
      src: files/zshrc
      dest: /home/onigiri/.zshrc
      owner: onigiri
      group: onigiri

  - name: copy .zsh_aliases file - arch
    copy:
      src: files/zsh_aliases_arch
      dest: /home/onigiri/.zsh_aliases
      owner: onigiri
      group: onigiri
    when: ansible_facts['os_family']|lower == 'archlinux'

  - name: copy .zsh_aliases file - deb
    copy:
      src: files/zsh_aliases_deb
      dest: /home/onigiri/.zsh_aliases
      owner: onigiri
      group: onigiri
    when: ansible_facts['os_family']|lower == 'debian'

  - name: copy .zsh_aliases file - fed
    copy:
      src: files/zsh_aliases_fed
      dest: /home/onigiri/.zsh_aliases
      owner: onigiri
      group: onigiri
    when: ansible_facts['os_family']|lower == 'fedora'

  - name: copy .zprofile file
    copy:
      src: files/zprofile
      dest: /home/onigiri/.zprofile
      owner: onigiri
      group: onigiri

  - name: change shell to zsh
    user: 
      name: onigiri
      shell: /usr/bin/zsh

#  - name: add ansible user
#    user:
#      name: tractor
#      system: yes
#
#  - name: set up sudo for ansible user
#    copy:
#      src: files/sudoer_tractor
#      dest: /etc/sudoers.d/tractor
#      owner: root
#      group: root
#      mode: 0440
#
#  - name: add ansible-pull cron job
#    cron:
#      name: ansible auto-provision
#      user: tractor
#      minute: "*/10"
#      job: ansible-pull -o -U https://gitlab.com/onigiri070/ansible_workstation.git 
